version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=seeya_db
      - POSTGRES_USER=postgres
      - NODE_ENV=docker
  web:
    build: .
    environment:
      - NODE_ENV=docker
    ports:
      - "1337:1337"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
